package o;

import java.util.List;
/* loaded from: classes-dex2jar.jar:o/cameraCopy.class */
public class cameraCopy {
    @infoContactPersonDialogEvent(c = "FlagAgreeDisclosure")
    public String A;
    @infoContactPersonDialogEvent(c = "EmergencyContactRelation")
    public String B;
    @infoContactPersonDialogEvent(c = "FlagAgreeAutodebet")
    public String C;
    @infoContactPersonDialogEvent(c = "EmergencyContactPhoneNumber")
    public String D;
    @infoContactPersonDialogEvent(c = "FlagSubmitSupplement")
    public String E;
    @infoContactPersonDialogEvent(c = "FlagGuest")
    public String F;
    @infoContactPersonDialogEvent(c = "Gender")
    public String G;
    @infoContactPersonDialogEvent(c = "FlagAgreeLifeInsurance")
    public String H;
    @infoContactPersonDialogEvent(c = "FlagBCAAccount")
    public String I;
    @infoContactPersonDialogEvent(c = "HmAddress")
    public String J;
    @infoContactPersonDialogEvent(c = "HmHouseStatus")
    public String K;
    @infoContactPersonDialogEvent(c = "HmKecamatan")
    public String L;
    @infoContactPersonDialogEvent(c = "HmCity")
    public String M;
    @infoContactPersonDialogEvent(c = "HmKelurahan")
    public String N;
    @infoContactPersonDialogEvent(c = "HmRW")
    public String O;
    @infoContactPersonDialogEvent(c = "HmStayPeriod")
    public String P;
    @infoContactPersonDialogEvent(c = "IdentityCardImg")
    public String Q;
    @infoContactPersonDialogEvent(c = "HmPostCode")
    public String R;
    @infoContactPersonDialogEvent(c = "HmRT")
    public String S;
    @infoContactPersonDialogEvent(c = "IdentityCardType")
    public String T;
    @infoContactPersonDialogEvent(c = "IMEI")
    public String U;
    @infoContactPersonDialogEvent(c = "LastEducation")
    public String V;
    @infoContactPersonDialogEvent(c = "LoginEmailAddr")
    public String W;
    @infoContactPersonDialogEvent(c = "IdentityCardNumber")
    public String X;
    @infoContactPersonDialogEvent(c = "MonthlyOtherIncome")
    public String Y;
    @infoContactPersonDialogEvent(c = "MaritalStatus")
    public String Z;
    @infoContactPersonDialogEvent(c = "AutodebetAccountNumber")
    public String a;
    @infoContactPersonDialogEvent(c = "MotherMaidenName")
    public String aa;
    @infoContactPersonDialogEvent(c = "MonthlyIncome")
    public String ab;
    @infoContactPersonDialogEvent(c = "MobileNumber")
    public String ac;
    @infoContactPersonDialogEvent(c = "OfficePosition")
    public String ad;
    @infoContactPersonDialogEvent(c = "Nationality")
    public String ae;
    @infoContactPersonDialogEvent(c = "OtherBankAccount")
    public List<read> af;
    @infoContactPersonDialogEvent(c = "NPWP")
    public String ag;
    @infoContactPersonDialogEvent(c = "NPWPImg")
    public String ah;
    @infoContactPersonDialogEvent(c = "PhoneNumber")
    public String ai;
    @infoContactPersonDialogEvent(c = "OtherBankCreditCard")
    public List<cameraCopy$MediaBrowserCompat$CustomActionResultReceiver> aj;
    @infoContactPersonDialogEvent(c = "PrevWorkPeriod")
    public String ak;
    @infoContactPersonDialogEvent(c = "PreferredMailingAddress")
    public String al;
    @infoContactPersonDialogEvent(c = "PrevCompanyName")
    public String am;
    @infoContactPersonDialogEvent(c = "SelectedCardOptions")
    public String an;
    @infoContactPersonDialogEvent(c = "ReferenceSalesCode")
    public String ao;
    @infoContactPersonDialogEvent(c = "ReferenceBranchCode")
    public String ap;
    @infoContactPersonDialogEvent(c = "ReferenceSalesName")
    public String aq;
    @infoContactPersonDialogEvent(c = "PromotionCode")
    public String ar;
    @infoContactPersonDialogEvent(c = "TotalSupplementCard")
    public String at;
    @infoContactPersonDialogEvent(c = "SupplementCard")
    public List<write> au;
    @infoContactPersonDialogEvent(c = "TotalDependent")
    public String av;
    @infoContactPersonDialogEvent(c = "SessionId")
    public String aw;
    @infoContactPersonDialogEvent(c = "BCADebitCardType")
    public String b;
    @infoContactPersonDialogEvent(c = "BCADebitCardNumber")
    public String c;
    @infoContactPersonDialogEvent(c = "AutodebetPercentage")
    public String d;
    @infoContactPersonDialogEvent(c = "BCAAccountNumber")
    public String e;
    @infoContactPersonDialogEvent(c = "CurrCompanyName")
    public String f;
    @infoContactPersonDialogEvent(c = "CurrOfficeAddress")
    public String g;
    @infoContactPersonDialogEvent(c = "BirthPlace")
    public String h;
    @infoContactPersonDialogEvent(c = "CurrOfficeBusinessField")
    public String i;
    @infoContactPersonDialogEvent(c = "BirthDate")
    public String j;
    @infoContactPersonDialogEvent(c = "CurrOfficeEmailAddress")
    public String k;
    @infoContactPersonDialogEvent(c = "CurrOfficeExtentionNumber")
    public String l;
    @infoContactPersonDialogEvent(c = "CurrOfficePhoneNumber")
    public String m;
    @infoContactPersonDialogEvent(c = "CurrOfficeCity")
    public String n;
    @infoContactPersonDialogEvent(c = "CurrOfficePostCode")

    /* renamed from: o  reason: collision with root package name */
    public String f135o;
    @infoContactPersonDialogEvent(c = "EmergencyContactAddress")
    public String p;
    @infoContactPersonDialogEvent(c = "CurrWorkPeriod")
    public String q;
    @infoContactPersonDialogEvent(c = "EmailAddr")
    public String r;
    @infoContactPersonDialogEvent(c = "CustomerName")
    public String s;
    @infoContactPersonDialogEvent(c = "CustomerFullName")
    public String t;
    @infoContactPersonDialogEvent(c = "EmergencyContactCity")
    public String u;
    @infoContactPersonDialogEvent(c = "EmergencyContactName")
    public String v;
    @infoContactPersonDialogEvent(c = "EmergencyContactOfficeExt")
    public String w;
    @infoContactPersonDialogEvent(c = "EmergencyContactMobileNumber")
    public String x;
    @infoContactPersonDialogEvent(c = "EmergencyContactBCACardNumber")
    public String y;
    @infoContactPersonDialogEvent(c = "EmergencyContactOfficePhone")
    public String z;

    /* loaded from: classes-dex2jar.jar:o/cameraCopy$read.class */
    public static final class read {
        @infoContactPersonDialogEvent(c = "AccountNumber")
        public String b;
        @infoContactPersonDialogEvent(c = "AccountType")
        public String c;
        @infoContactPersonDialogEvent(c = "BankName")
        public String d;
    }

    /* loaded from: classes-dex2jar.jar:o/cameraCopy$write.class */
    public static final class write {
        @infoContactPersonDialogEvent(c = "BirthDate")
        public String a;
        @infoContactPersonDialogEvent(c = "CustomerName")
        public String b;
        @infoContactPersonDialogEvent(c = "Gender")
        public String c;
        @infoContactPersonDialogEvent(c = "JobSector")
        public String d;
        @infoContactPersonDialogEvent(c = "IdentityCardImg")
        public String e;
        @infoContactPersonDialogEvent(c = "Occupation")
        public String f;
        @infoContactPersonDialogEvent(c = "MobileNumber")
        public String g;
        @infoContactPersonDialogEvent(c = "SupplementCardOptions")
        public String h;
        @infoContactPersonDialogEvent(c = "Relationship")
        public String i;
        @infoContactPersonDialogEvent(c = "SupplementCardLimit")
        public String j;
    }
}
