package o;

import java.util.List;
/* loaded from: classes-dex2jar.jar:o/cancelPicture.class */
public class cancelPicture {
    @infoContactPersonDialogEvent(c = "ImageList")
    public List<InfoPromoORActivity_ViewBinding> A;
    @infoContactPersonDialogEvent(c = "HPhoneMB")
    public String B;
    @infoContactPersonDialogEvent(c = "IMEI")
    public String C;
    @infoContactPersonDialogEvent(c = "IncomeSource")
    public String D;
    @infoContactPersonDialogEvent(c = "KitasKitapFlag")
    public String E;
    @infoContactPersonDialogEvent(c = "JobOthers")
    public String F;
    @infoContactPersonDialogEvent(c = "KitasKitapExpDate")
    public String G;
    @infoContactPersonDialogEvent(c = "Job")
    public String H;
    @infoContactPersonDialogEvent(c = "KitasKitapNumber")
    public String I;
    @infoContactPersonDialogEvent(c = "KodeAreaTeleponRumah")
    public String J;
    @infoContactPersonDialogEvent(c = "Language")
    public String K;
    @infoContactPersonDialogEvent(c = "MaritalStatus")
    public String L;
    @infoContactPersonDialogEvent(c = "KodeNegaraHandphone")
    public String M;
    @infoContactPersonDialogEvent(c = "KodeNegaraTeleponRumah")
    public String N;
    @infoContactPersonDialogEvent(c = "MotherMaidenName")
    public String O;
    @infoContactPersonDialogEvent(c = "NPWP")
    public String P;
    @infoContactPersonDialogEvent(c = "Name")
    public String Q;
    @infoContactPersonDialogEvent(c = "NPWPNumber")
    public String R;
    @infoContactPersonDialogEvent(c = "NumberID")
    public String S;
    @infoContactPersonDialogEvent(c = "OfficeName")
    public String T;
    @infoContactPersonDialogEvent(c = "OfficeCity")
    public String U;
    @infoContactPersonDialogEvent(c = "Occupation")
    public String V;
    @infoContactPersonDialogEvent(c = "OfficePostCode")
    public String W;
    @infoContactPersonDialogEvent(c = "OfficeAddress")
    public String X;
    @infoContactPersonDialogEvent(c = "PurposePemRek")
    public String Y;
    @infoContactPersonDialogEvent(c = "OfficeProvince")
    public String Z;
    @infoContactPersonDialogEvent(c = "Citizen")
    public String a;
    @infoContactPersonDialogEvent(c = "POB")
    public String aa;
    @infoContactPersonDialogEvent(c = "OldCustFlag")
    public String ab;
    @infoContactPersonDialogEvent(c = "Religion")
    public String ac;
    @infoContactPersonDialogEvent(c = "ResProvince")
    public String ad;
    @infoContactPersonDialogEvent(c = "ResPostCode")
    public String ae;
    @infoContactPersonDialogEvent(c = "ResAddress")
    public String af;
    @infoContactPersonDialogEvent(c = "ResCountry")
    public String ag;
    @infoContactPersonDialogEvent(c = "ResCity")
    public String ah;
    @infoContactPersonDialogEvent(c = "Salary")
    public String ai;
    @infoContactPersonDialogEvent(c = "ResRW")
    public String aj;
    @infoContactPersonDialogEvent(c = "ResSubDistrict")
    public String ak;
    @infoContactPersonDialogEvent(c = "ResRT")
    public String al;
    @infoContactPersonDialogEvent(c = "ResVillage")
    public String am;
    @infoContactPersonDialogEvent(c = "TypeID")
    public String ao;
    @infoContactPersonDialogEvent(c = "Sex")
    public String ap;
    @infoContactPersonDialogEvent(c = "SessionId")
    public String ar;
    @infoContactPersonDialogEvent(c = "COB")
    public String b;
    @infoContactPersonDialogEvent(c = "AcctType")
    public String c;
    @infoContactPersonDialogEvent(c = "BusinessField")
    public String d;
    @infoContactPersonDialogEvent(c = "DebitCardType")
    public String e;
    @infoContactPersonDialogEvent(c = "FlagDifResidency")
    public String f;
    @infoContactPersonDialogEvent(c = "DollarCurrCode")
    public String g;
    @infoContactPersonDialogEvent(c = "ExpID")
    public String h;
    @infoContactPersonDialogEvent(c = "DOB")
    public String i;
    @infoContactPersonDialogEvent(c = "Email")
    public String j;
    @infoContactPersonDialogEvent(c = "FlagMB")
    public String k;
    @infoContactPersonDialogEvent(c = "HandPhoneNumber")
    public String l;
    @infoContactPersonDialogEvent(c = "FlagIB")
    public String m;
    @infoContactPersonDialogEvent(c = "HmAddress")
    public String n;
    @infoContactPersonDialogEvent(c = "FlagGuest")

    /* renamed from: o  reason: collision with root package name */
    public String f136o;
    @infoContactPersonDialogEvent(c = "HmPhoneNumber")
    public String p;
    @infoContactPersonDialogEvent(c = "HmPostCode")
    public String q;
    @infoContactPersonDialogEvent(c = "HmCountry")
    public String r;
    @infoContactPersonDialogEvent(c = "HmProvince")
    public String s;
    @infoContactPersonDialogEvent(c = "HmCity")
    public String t;
    @infoContactPersonDialogEvent(c = "HmRT")
    public String u;
    @infoContactPersonDialogEvent(c = "HmRW")
    public String v;
    @infoContactPersonDialogEvent(c = "HPhoneIB")
    public String w;
    @infoContactPersonDialogEvent(c = "HmSubDistrict")
    public String x;
    @infoContactPersonDialogEvent(c = "HmVillage")
    public String y;
    @infoContactPersonDialogEvent(c = "IncomeSourceOthers")
    public String z;
}
