package o;

import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.ScrollView;
import android.widget.TextView;
/* loaded from: classes-dex2jar.jar:o/KantorCabangROAdapter$KantorCabangROVH.class */
public final class KantorCabangROAdapter$KantorCabangROVH {
    public final ScrollView A;
    public final RadioGroup B;
    public final RadioButton C;
    public final RadioGroup D;
    public final LogoutDialog_ViewBinding E;
    public final LogoutDialog_ViewBinding F;
    public final ScrollView G;
    public final LogoutDialog_ViewBinding H;
    public final LogoutDialog_ViewBinding I;
    public final LogoutDialog_ViewBinding J;
    public final LogoutDialog_ViewBinding K;
    public final LogoutDialog_ViewBinding L;
    public final LogoutDialog_ViewBinding M;
    public final LogoutDialog_ViewBinding N;
    public final setTypeface O;
    public final TextView P;
    public final LogoutDialog_ViewBinding Q;
    public final LogoutDialog_ViewBinding R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;
    public final EditText a;
    public final TextView aa;
    public final TextView ab;
    public final TextView ac;
    public final TextView af;
    public final TextView ah;
    public final CheckBox b;
    public final Button c;
    public final EditText d;
    public final EditText e;
    public final EditText f;
    public final EditText g;
    public final AutoCompleteTextView h;
    public final AutoCompleteTextView i;
    public final EditText j;
    public final ImageView k;
    public final EditText l;
    public final EditText m;
    public final setAnnualFeeAddOnDisplayAmount n;

    /* renamed from: o */
    public final LinearLayout f95o;
    public final LinearLayout p;
    public final LinearLayout q;
    public final LinearLayout r;
    public final LinearLayout s;
    public final LinearLayout t;
    public final RadioButton u;
    public final RadioButton v;
    public final RadioButton w;
    public final RadioButton x;
    public final RadioButton y;
    public final RadioGroup z;

    public KantorCabangROAdapter$KantorCabangROVH(ScrollView scrollView, Button button, CheckBox checkBox, EditText editText, EditText editText2, EditText editText3, EditText editText4, AutoCompleteTextView autoCompleteTextView, EditText editText5, EditText editText6, AutoCompleteTextView autoCompleteTextView2, setAnnualFeeAddOnDisplayAmount setannualfeeaddondisplayamount, EditText editText7, EditText editText8, ImageView imageView, LinearLayout linearLayout, LinearLayout linearLayout2, LinearLayout linearLayout3, LinearLayout linearLayout4, LinearLayout linearLayout5, LinearLayout linearLayout6, RadioButton radioButton, RadioButton radioButton2, RadioButton radioButton3, RadioButton radioButton4, RadioButton radioButton5, RadioButton radioButton6, RadioGroup radioGroup, RadioGroup radioGroup2, RadioGroup radioGroup3, ScrollView scrollView2, LogoutDialog_ViewBinding logoutDialog_ViewBinding, LogoutDialog_ViewBinding logoutDialog_ViewBinding2, LogoutDialog_ViewBinding logoutDialog_ViewBinding3, LogoutDialog_ViewBinding logoutDialog_ViewBinding4, LogoutDialog_ViewBinding logoutDialog_ViewBinding5, LogoutDialog_ViewBinding logoutDialog_ViewBinding6, LogoutDialog_ViewBinding logoutDialog_ViewBinding7, LogoutDialog_ViewBinding logoutDialog_ViewBinding8, LogoutDialog_ViewBinding logoutDialog_ViewBinding9, LogoutDialog_ViewBinding logoutDialog_ViewBinding10, LogoutDialog_ViewBinding logoutDialog_ViewBinding11, TextView textView, setTypeface settypeface, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14) {
        this.A = scrollView;
        this.c = button;
        this.b = checkBox;
        this.e = editText;
        this.d = editText2;
        this.a = editText3;
        this.g = editText4;
        this.i = autoCompleteTextView;
        this.f = editText5;
        this.j = editText6;
        this.h = autoCompleteTextView2;
        this.n = setannualfeeaddondisplayamount;
        this.m = editText7;
        this.l = editText8;
        this.k = imageView;
        this.f95o = linearLayout;
        this.p = linearLayout2;
        this.r = linearLayout3;
        this.s = linearLayout4;
        this.t = linearLayout5;
        this.q = linearLayout6;
        this.u = radioButton;
        this.y = radioButton2;
        this.v = radioButton3;
        this.x = radioButton4;
        this.w = radioButton5;
        this.C = radioButton6;
        this.B = radioGroup;
        this.z = radioGroup2;
        this.D = radioGroup3;
        this.G = scrollView2;
        this.F = logoutDialog_ViewBinding;
        this.H = logoutDialog_ViewBinding2;
        this.E = logoutDialog_ViewBinding3;
        this.I = logoutDialog_ViewBinding4;
        this.M = logoutDialog_ViewBinding5;
        this.L = logoutDialog_ViewBinding6;
        this.N = logoutDialog_ViewBinding7;
        this.J = logoutDialog_ViewBinding8;
        this.K = logoutDialog_ViewBinding9;
        this.R = logoutDialog_ViewBinding10;
        this.Q = logoutDialog_ViewBinding11;
        this.P = textView;
        this.O = settypeface;
        this.S = textView2;
        this.W = textView3;
        this.T = textView4;
        this.U = textView5;
        this.X = textView6;
        this.V = textView7;
        this.ab = textView8;
        this.ac = textView9;
        this.aa = textView10;
        this.Y = textView11;
        this.Z = textView12;
        this.af = textView13;
        this.ah = textView14;
    }
}
