package o;

import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.Space;
import android.widget.TextView;
/* loaded from: classes-dex2jar.jar:o/ListKotaAdapter$ListKotaAdapterVH.class */
public final class ListKotaAdapter$ListKotaAdapterVH {
    public final LogoutDialog_ViewBinding A;
    public final LogoutDialog_ViewBinding B;
    public final LogoutDialog_ViewBinding C;
    public final LogoutDialog_ViewBinding D;
    public final LogoutDialog_ViewBinding E;
    public final LogoutDialog_ViewBinding F;
    public final LogoutDialog_ViewBinding G;
    public final TextView H;
    public final LogoutDialog_ViewBinding I;
    public final TextView J;
    public final TextView K;
    public final TextView L;
    public final TextView M;
    public final TextView N;
    public final TextView O;
    public final TextView P;
    public final TextView Q;
    public final TextView R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final LinearLayout Y;
    public final setTypeface Z;
    public final LinearLayout a;
    public final TextView aa;
    public final RelativeLayout ab;
    public final RelativeLayout ac;
    public final LinearLayout ad;
    public final RelativeLayout ae;
    public final RelativeLayout af;
    public final RelativeLayout ag;
    public final RelativeLayout ah;
    public final LinearLayout b;
    public final LinearLayout c;
    public final LinearLayout d;
    public final LinearLayout e;
    public final LinearLayout f;
    public final LinearLayout g;
    public final LinearLayout h;
    public final LinearLayout i;
    public final LinearLayout j;
    public final EditText k;
    public final EditText l;
    public final EditText m;
    public final setTypeface n;

    /* renamed from: o */
    public final EditText f117o;
    public final EditText p;
    public final EditText q;
    public final EditText r;
    public final EditText s;
    public final EditText t;
    public final LinearLayout u;
    public final setMaxHeight v;
    public final Space w;
    public final setDropDownHorizontalOffset x;
    public final setRequestHeaders y;
    public final LogoutDialog_ViewBinding z;

    public ListKotaAdapter$ListKotaAdapterVH(setMaxHeight setmaxheight, LinearLayout linearLayout, LinearLayout linearLayout2, LinearLayout linearLayout3, LinearLayout linearLayout4, LinearLayout linearLayout5, LinearLayout linearLayout6, LinearLayout linearLayout7, LinearLayout linearLayout8, LinearLayout linearLayout9, LinearLayout linearLayout10, setTypeface settypeface, EditText editText, EditText editText2, EditText editText3, EditText editText4, EditText editText5, EditText editText6, EditText editText7, EditText editText8, EditText editText9, setRequestHeaders setrequestheaders, setDropDownHorizontalOffset setdropdownhorizontaloffset, LinearLayout linearLayout11, Space space, LogoutDialog_ViewBinding logoutDialog_ViewBinding, LogoutDialog_ViewBinding logoutDialog_ViewBinding2, LogoutDialog_ViewBinding logoutDialog_ViewBinding3, LogoutDialog_ViewBinding logoutDialog_ViewBinding4, LogoutDialog_ViewBinding logoutDialog_ViewBinding5, LogoutDialog_ViewBinding logoutDialog_ViewBinding6, LogoutDialog_ViewBinding logoutDialog_ViewBinding7, LogoutDialog_ViewBinding logoutDialog_ViewBinding8, LogoutDialog_ViewBinding logoutDialog_ViewBinding9, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, setTypeface settypeface2, TextView textView17, RelativeLayout relativeLayout, LinearLayout linearLayout12, RelativeLayout relativeLayout2, RelativeLayout relativeLayout3, RelativeLayout relativeLayout4, LinearLayout linearLayout13, RelativeLayout relativeLayout5, RelativeLayout relativeLayout6) {
        this.v = setmaxheight;
        this.d = linearLayout;
        this.a = linearLayout2;
        this.e = linearLayout3;
        this.b = linearLayout4;
        this.c = linearLayout5;
        this.j = linearLayout6;
        this.i = linearLayout7;
        this.h = linearLayout8;
        this.f = linearLayout9;
        this.g = linearLayout10;
        this.n = settypeface;
        this.l = editText;
        this.k = editText2;
        this.m = editText3;
        this.f117o = editText4;
        this.s = editText5;
        this.q = editText6;
        this.p = editText7;
        this.r = editText8;
        this.t = editText9;
        this.y = setrequestheaders;
        this.x = setdropdownhorizontaloffset;
        this.u = linearLayout11;
        this.w = space;
        this.z = logoutDialog_ViewBinding;
        this.A = logoutDialog_ViewBinding2;
        this.B = logoutDialog_ViewBinding3;
        this.D = logoutDialog_ViewBinding4;
        this.C = logoutDialog_ViewBinding5;
        this.G = logoutDialog_ViewBinding6;
        this.F = logoutDialog_ViewBinding7;
        this.I = logoutDialog_ViewBinding8;
        this.E = logoutDialog_ViewBinding9;
        this.H = textView;
        this.J = textView2;
        this.M = textView3;
        this.N = textView4;
        this.K = textView5;
        this.L = textView6;
        this.O = textView7;
        this.Q = textView8;
        this.R = textView9;
        this.S = textView10;
        this.P = textView11;
        this.X = textView12;
        this.W = textView13;
        this.T = textView14;
        this.V = textView15;
        this.U = textView16;
        this.Z = settypeface2;
        this.aa = textView17;
        this.ac = relativeLayout;
        this.Y = linearLayout12;
        this.ab = relativeLayout2;
        this.ae = relativeLayout3;
        this.ag = relativeLayout4;
        this.ad = linearLayout13;
        this.ah = relativeLayout5;
        this.af = relativeLayout6;
    }
}
