package o;

import com.google.android.gms.common.api.Status;
import o.realmGet$occupationFlagFreeText;
import o.realmGet$oldCustFlag;
/* loaded from: classes-dex2jar.jar:o/realmSet$motherMaidenName.class */
public final class realmSet$motherMaidenName<R extends realmGet$oldCustFlag> extends realmGet$occupationFlagFreeText<R> {
    private final Status e;

    @Override // o.realmGet$occupationFlagFreeText
    public final void b(realmGet$occupationFlagFreeText.IconCompatParcelizer iconCompatParcelizer) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public final Status e() {
        return this.e;
    }

    @Override // o.realmGet$occupationFlagFreeText
    public final void e(realmGet$officeName<? super R> realmget_officename) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
